# Generated by Django 4.1.5 on 2023-01-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_student_password_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Confirm_Password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
